### ISSUE TITLE
Create basic UI of Android App & download app on Android phone (13 Story Points)

### ISSUE THREAD

**Issue by Fabzyzy** [iluvpomeranians/ClearBreath_Portable_Breathalyzer#6]
### User Story
As a developer, I need to create the initial structure of the Android app, including the main activities and basic UI components.
**Tasks**
- [ ] Set up a new Android project in Android Studio.
- [ ] Set up the layouts of the main activity and other directly adjacent activities.
- [ ] Add necessary permissions and configurations in the manifest file.
- [ ] Set placeholder values for future testing of the device with android app.
- [ ] Download app on given Android phone.
- [ ] Test its features and functionality.
